DROP DATABASE IF EXISTS ems;
CREATE DATABASE ems;

USE ems;

CREATE TABLE department (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  team VARCHAR(30) UNIQUE NOT NULL
);

CREATE TABLE role (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  position VARCHAR(30) UNIQUE NOT NULL,
  salary DECIMAL UNSIGNED NOT NULL,
  departmentid INT UNSIGNED NOT NULL,
  INDEX depindex (departmentid),
  CONSTRAINT fkdepartment FOREIGN KEY (departmentid) REFERENCES department(id) ON DELETE CASCADE
);

CREATE TABLE employee (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  firstname VARCHAR(30) NOT NULL,
  lastname VARCHAR(30) NOT NULL,
  roleid INT UNSIGNED NOT NULL,
  INDEX roleindex (roleid),
  CONSTRAINT fkrole FOREIGN KEY (roleid) REFERENCES role(id) ON DELETE CASCADE
);